import React, { useState } from "react";
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";
import HighchartsSankey from "highcharts/modules/sankey";
import HighchartsWheel from "highcharts/modules/dependency-wheel";

HighchartsSankey(Highcharts);
HighchartsWheel(Highcharts);


const App = () => {
  //set the chart type to start out as sankey  
  const [type, setType] = useState("sankey");

  //handle button click to change chart type
  const handleTypeChange = (type) => {
    if (type === "sankey") {
      setType("dependencywheel");
    } else {
      setType("sankey");
    }
  };

  //chart settings
  const options = {
    title: {
      text: "Asia Pacific to Europe"
    },
    chart: {
      type
    },
    series: [
        {
            keys: ["from", "to", "weight"],
            data: [
                ["Afghanistan","Albania",5  ],
                ["Afghanistan","Armenia",5  ],
                ["Afghanistan","Austria",42685  ],
                ["Afghanistan","Azerbaijan",1189  ],
                ["Afghanistan","Belgium",5859  ],
                ["Afghanistan","Belarus",127  ],
                ["Afghanistan","Bulgaria",300  ],
                ["Afghanistan","Cyprus",17  ],
                ["Afghanistan","Czechia",150  ],
                ["Afghanistan","Denmark",1696  ],
                ["Afghanistan","Estonia",20  ],
                ["Afghanistan","Finland",3652  ],
                ["Afghanistan","France",49990  ],
                ["Afghanistan","United Kingdom of Great Britain and Northern Ireland",9642  ],
                ["Afghanistan","Georgia",20  ],
                ["Afghanistan","Germany",159409  ],
                ["Afghanistan","Greece",28543  ],
                ["Afghanistan","Croatia",93  ],
                ["Afghanistan","Hungary",1467  ],
                ["Afghanistan","Iceland",179  ],
                ["Afghanistan","Ireland",549  ],
                ["Afghanistan","Italy",15561  ],
                ["Afghanistan","Liechtenstein",5  ],
                ["Afghanistan","Lithuania",230  ],
                ["Afghanistan","Luxembourg",427  ],
                ["Afghanistan","Latvia",81  ],
                ["Afghanistan","North Macedonia",8  ],
                ["Afghanistan","Rep. of Moldova",12  ],
                ["Afghanistan","Netherlands",6660  ],
                ["Afghanistan","Norway",3448  ],
                ["Afghanistan","Poland",846  ],
                ["Afghanistan","Portugal",121  ],
                ["Afghanistan","Romania",332  ],
                ["Afghanistan","Russian Federation",921  ],
                ["Afghanistan","Spain",1188  ],
                ["Afghanistan","Serbia and Kosovo: S/RES/1244 (1999)",27  ],
                ["Afghanistan","Slovakia",319  ],
                ["Afghanistan","Slovenia",60  ],
                ["Afghanistan","Sweden",27562  ],
                ["Afghanistan","Switzerland",15060  ],
                ["Afghanistan","Türkiye",7647  ],
                ["Afghanistan","Ukraine",890  ],
                ["Australia","United Kingdom of Great Britain and Northern Ireland",5  ],
                ["Australia","Germany",6  ],
                ["Bangladesh","Austria",360  ],
                ["Bangladesh","Belgium",21  ],
                ["Bangladesh","Bulgaria",8  ],
                ["Bangladesh","Cyprus",10  ],
                ["Bangladesh","Denmark",19  ],
                ["Bangladesh","Finland",25  ],
                ["Bangladesh","France",8608  ],
                ["Bangladesh","United Kingdom of Great Britain and Northern Ireland",1781  ],
                ["Bangladesh","Germany",816  ],
                ["Bangladesh","Greece",328  ],
                ["Bangladesh","Croatia",7  ],
                ["Bangladesh","Hungary",11  ],
                ["Bangladesh","Iceland",5  ],
                ["Bangladesh","Ireland",101  ],
                ["Bangladesh","Italy",5046  ],
                ["Bangladesh","Malta",14  ],
                ["Bangladesh","Netherlands",43  ],
                ["Bangladesh","Norway",5  ],
                ["Bangladesh","Poland",6  ],
                ["Bangladesh","Portugal",6  ],
                ["Bangladesh","Romania",11  ],
                ["Bangladesh","Russian Federation",5  ],
                ["Bangladesh","Spain",21  ],
                ["Bangladesh","Sweden",250  ],
                ["Bangladesh","Switzerland",43  ],
                ["Bangladesh","Ukraine",5  ],
                ["Bhutan","France",173  ],
                ["Bhutan","United Kingdom of Great Britain and Northern Ireland",23  ],
                ["Bhutan","Germany",21  ],
                ["Bhutan","Ireland",10  ],
                ["Bhutan","Luxembourg",5  ],
                ["Bhutan","Netherlands",42  ],
                ["Cambodia","Belgium",13  ],
                ["Cambodia","Finland",5  ],
                ["Cambodia","France",11059  ],
                ["Cambodia","Germany",30  ],
                ["Cambodia","Netherlands",6  ],
                ["Cambodia","Slovakia",5  ],
                ["Cambodia","Switzerland",279  ],
                ["China","Albania",14  ],
                ["China","Austria",642  ],
                ["China","Belgium",1206  ],
                ["China","Cyprus",5  ],
                ["China","Czechia",62  ],
                ["China","Denmark",19  ],
                ["China","Finland",190  ],
                ["China","France",10015  ],
                ["China","United Kingdom of Great Britain and Northern Ireland",1026  ],
                ["China","Germany",2019  ],
                ["China","Greece",114  ],
                ["China","Hungary",5  ],
                ["China","Iceland",5  ],
                ["China","Ireland",71  ],
                ["China","Italy",397  ],
                ["China","Liechtenstein",35  ],
                ["China","Luxembourg",7  ],
                ["China","Latvia",5  ],
                ["China","Malta",17  ],
                ["China","Netherlands",770  ],
                ["China","Norway",281  ],
                ["China","Poland",17  ],
                ["China","Portugal",6  ],
                ["China","Romania",5  ],
                ["China","Russian Federation",23  ],
                ["China","Spain",32  ],
                ["China","Slovakia",5  ],
                ["China","Sweden",248  ],
                ["China","Switzerland",2443  ],
                ["Fiji","United Kingdom of Great Britain and Northern Ireland",8  ],
                ["China, Hong Kong SAR","United Kingdom of Great Britain and Northern Ireland",15  ],
                ["China, Hong Kong SAR","Italy",48  ],
                ["India","Austria",37  ],
                ["India","Belgium",14  ],
                ["India","Bulgaria",5  ],
                ["India","Cyprus",10  ],
                ["India","Denmark",5  ],
                ["India","Finland",5  ],
                ["India","France",319  ],
                ["India","United Kingdom of Great Britain and Northern Ireland",508  ],
                ["India","Germany",414  ],
                ["India","Greece",40  ],
                ["India","Ireland",16  ],
                ["India","Italy",252  ],
                ["India","Netherlands",6  ],
                ["India","Romania",5  ],
                ["India","Spain",12  ],
                ["India","Sweden",20  ],
                ["India","Switzerland",33  ],
                ["India","Ukraine",7  ],
                ["Indonesia","Finland",5  ],
                ["Indonesia","France",9  ],
                ["Indonesia","United Kingdom of Great Britain and Northern Ireland",41  ],
                ["Indonesia","Germany",16  ],
                ["Indonesia","Greece",14  ],
                ["Indonesia","Ireland",5  ],
                ["Indonesia","Netherlands",11  ],
                ["Indonesia","Sweden",15  ],
                ["Iran (Islamic Rep. of)","Armenia",139  ],
                ["Iran (Islamic Rep. of)","Austria",7209  ],
                ["Iran (Islamic Rep. of)","Azerbaijan",52  ],
                ["Iran (Islamic Rep. of)","Belgium",1843  ],
                ["Iran (Islamic Rep. of)","Belarus",5  ],
                ["Iran (Islamic Rep. of)","Bosnia and Herzegovina",5  ],
                ["Iran (Islamic Rep. of)","Bulgaria",81  ],
                ["Iran (Islamic Rep. of)","Cyprus",624  ],
                ["Iran (Islamic Rep. of)","Czechia",6  ],
                ["Iran (Islamic Rep. of)","Denmark",2790  ],
                ["Iran (Islamic Rep. of)","Estonia",5  ],
                ["Iran (Islamic Rep. of)","Finland",966  ],
                ["Iran (Islamic Rep. of)","France",3967  ],
                ["Iran (Islamic Rep. of)","United Kingdom of Great Britain and Northern Ireland",21434  ],
                ["Iran (Islamic Rep. of)","Georgia",44  ],
                ["Iran (Islamic Rep. of)","Germany",46223  ],
                ["Iran (Islamic Rep. of)","Greece",3201  ],
                ["Iran (Islamic Rep. of)","Croatia",41  ],
                ["Iran (Islamic Rep. of)","Hungary",193  ],
                ["Iran (Islamic Rep. of)","Iceland",95  ],
                ["Iran (Islamic Rep. of)","Ireland",155  ],
                ["Iran (Islamic Rep. of)","Italy",1278  ],
                ["Iran (Islamic Rep. of)","Liechtenstein",11  ],
                ["Iran (Islamic Rep. of)","Lithuania",13  ],
                ["Iran (Islamic Rep. of)","Luxembourg",211  ],
                ["Iran (Islamic Rep. of)","Latvia",17  ],
                ["Iran (Islamic Rep. of)","Montenegro",17  ],
                ["Iran (Islamic Rep. of)","Malta",31  ],
                ["Iran (Islamic Rep. of)","Netherlands",5438  ],
                ["Iran (Islamic Rep. of)","Norway",1496  ],
                ["Iran (Islamic Rep. of)","Poland",50  ],
                ["Iran (Islamic Rep. of)","Portugal",50  ],
                ["Iran (Islamic Rep. of)","Romania",120  ],
                ["Iran (Islamic Rep. of)","Russian Federation",5  ],
                ["Iran (Islamic Rep. of)","Spain",87  ],
                ["Iran (Islamic Rep. of)","Serbia and Kosovo: S/RES/1244 (1999)",19  ],
                ["Iran (Islamic Rep. of)","Slovakia",39  ],
                ["Iran (Islamic Rep. of)","Slovenia",80  ],
                ["Iran (Islamic Rep. of)","Sweden",7350  ],
                ["Iran (Islamic Rep. of)","Switzerland",2246  ],
                ["Iran (Islamic Rep. of)","Türkiye",3942  ],
                ["Iran (Islamic Rep. of)","Ukraine",74  ],
                ["Japan","Germany",23  ],
                ["Kazakhstan","Austria",108  ],
                ["Kazakhstan","Belgium",60  ],
                ["Kazakhstan","Cyprus",5  ],
                ["Kazakhstan","Czechia",76  ],
                ["Kazakhstan","Finland",8  ],
                ["Kazakhstan","France",1047  ],
                ["Kazakhstan","United Kingdom of Great Britain and Northern Ireland",42  ],
                ["Kazakhstan","Georgia",5  ],
                ["Kazakhstan","Germany",112  ],
                ["Kazakhstan","Greece",5  ],
                ["Kazakhstan","Croatia",5  ],
                ["Kazakhstan","Iceland",5  ],
                ["Kazakhstan","Ireland",18  ],
                ["Kazakhstan","Latvia",5  ],
                ["Kazakhstan","Netherlands",48  ],
                ["Kazakhstan","Norway",10  ],
                ["Kazakhstan","Poland",40  ],
                ["Kazakhstan","Russian Federation",31  ],
                ["Kazakhstan","Spain",16  ],
                ["Kazakhstan","Slovenia",20  ],
                ["Kazakhstan","Sweden",203  ],
                ["Kazakhstan","Switzerland",28  ],
                ["Kazakhstan","Ukraine",9  ],
                ["Kyrgyzstan","Austria",117  ],
                ["Kyrgyzstan","Belgium",70  ],
                ["Kyrgyzstan","Cyprus",5  ],
                ["Kyrgyzstan","Czechia",18  ],
                ["Kyrgyzstan","Denmark",5  ],
                ["Kyrgyzstan","Finland",20  ],
                ["Kyrgyzstan","France",526  ],
                ["Kyrgyzstan","United Kingdom of Great Britain and Northern Ireland",38  ],
                ["Kyrgyzstan","Germany",248  ],
                ["Kyrgyzstan","Ireland",5  ],
                ["Kyrgyzstan","Italy",5  ],
                ["Kyrgyzstan","Latvia",5  ],
                ["Kyrgyzstan","Rep. of Moldova",10  ],
                ["Kyrgyzstan","Netherlands",12  ],
                ["Kyrgyzstan","Norway",12  ],
                ["Kyrgyzstan","Poland",32  ],
                ["Kyrgyzstan","Russian Federation",35  ],
                ["Kyrgyzstan","Spain",6  ],
                ["Kyrgyzstan","Sweden",154  ],
                ["Kyrgyzstan","Switzerland",16  ],
                ["Kyrgyzstan","Ukraine",11  ],
                ["Rep. of Korea","United Kingdom of Great Britain and Northern Ireland",5  ],
                ["Rep. of Korea","Germany",22  ],
                ["Rep. of Korea","Russian Federation",5  ],
                ["Rep. of Korea","Sweden",7  ],
                ["Dem. People's Rep. of Korea","Belgium",32  ],
                ["Dem. People's Rep. of Korea","United Kingdom of Great Britain and Northern Ireland",51  ],
                ["Dem. People's Rep. of Korea","Germany",89  ],
                ["Dem. People's Rep. of Korea","Ireland",9  ],
                ["Dem. People's Rep. of Korea","Luxembourg",11  ],
                ["Dem. People's Rep. of Korea","Netherlands",27  ],
                ["Dem. People's Rep. of Korea","Russian Federation",43  ],
                ["Lao People's Dem. Rep.","Belgium",10  ],
                ["Lao People's Dem. Rep.","France",6532  ],
                ["Lao People's Dem. Rep.","United Kingdom of Great Britain and Northern Ireland",5  ],
                ["Lao People's Dem. Rep.","Germany",40  ],
                ["Lao People's Dem. Rep.","Poland",5  ],
                ["Lao People's Dem. Rep.","Switzerland",107  ],
                ["Sri Lanka","Austria",71  ],
                ["Sri Lanka","Belgium",309  ],
                ["Sri Lanka","Cyprus",29  ],
                ["Sri Lanka","Czechia",7  ],
                ["Sri Lanka","Denmark",35  ],
                ["Sri Lanka","Estonia",5  ],
                ["Sri Lanka","Finland",33  ],
                ["Sri Lanka","France",33792  ],
                ["Sri Lanka","United Kingdom of Great Britain and Northern Ireland",4668  ],
                ["Sri Lanka","Germany",3591  ],
                ["Sri Lanka","Greece",55  ],
                ["Sri Lanka","Hungary",11  ],
                ["Sri Lanka","Iceland",5  ],
                ["Sri Lanka","Ireland",25  ],
                ["Sri Lanka","Italy",362  ],
                ["Sri Lanka","Lithuania",10  ],
                ["Sri Lanka","Luxembourg",5  ],
                ["Sri Lanka","Latvia",5  ],
                ["Sri Lanka","Malta",7  ],
                ["Sri Lanka","Netherlands",290  ],
                ["Sri Lanka","Norway",45  ],
                ["Sri Lanka","Poland",11  ],
                ["Sri Lanka","Portugal",33  ],
                ["Sri Lanka","Spain",67  ],
                ["Sri Lanka","Sweden",27  ],
                ["Sri Lanka","Switzerland",6059  ],
                ["Sri Lanka","Ukraine",8  ],
                ["Malaysia","France",28  ],
                ["Malaysia","United Kingdom of Great Britain and Northern Ireland",307  ],
                ["Malaysia","Germany",19  ],
                ["Malaysia","Ireland",9  ],
                ["Malaysia","Netherlands",8  ],
                ["Malaysia","Sweden",14  ],
                ["Mongolia","Austria",116  ],
                ["Mongolia","Czechia",10  ],
                ["Mongolia","France",832  ],
                ["Mongolia","United Kingdom of Great Britain and Northern Ireland",53  ],
                ["Mongolia","Germany",235  ],
                ["Mongolia","Ireland",8  ],
                ["Mongolia","Netherlands",28  ],
                ["Mongolia","Spain",5  ],
                ["Mongolia","Sweden",240  ],
                ["Mongolia","Switzerland",176  ],
                ["Myanmar","Austria",32  ],
                ["Myanmar","Belgium",8  ],
                ["Myanmar","Czechia",149  ],
                ["Myanmar","Denmark",13  ],
                ["Myanmar","Finland",32  ],
                ["Myanmar","France",355  ],
                ["Myanmar","United Kingdom of Great Britain and Northern Ireland",367  ],
                ["Myanmar","Germany",890  ],
                ["Myanmar","Greece",100  ],
                ["Myanmar","Ireland",13  ],
                ["Myanmar","Italy",5  ],
                ["Myanmar","Netherlands",203  ],
                ["Myanmar","Norway",22  ],
                ["Myanmar","Romania",30  ],
                ["Myanmar","Spain",8  ],
                ["Myanmar","Sweden",6  ],
                ["Myanmar","Switzerland",41  ],
                ["Nepal","Austria",18  ],
                ["Nepal","Belgium",6  ],
                ["Nepal","Denmark",5  ],
                ["Nepal","France",217  ],
                ["Nepal","United Kingdom of Great Britain and Northern Ireland",63  ],
                ["Nepal","Germany",61  ],
                ["Nepal","Greece",28  ],
                ["Nepal","Hungary",10  ],
                ["Nepal","Ireland",9  ],
                ["Nepal","Italy",15  ],
                ["Nepal","Netherlands",101  ],
                ["Nepal","Norway",5  ],
                ["Nepal","Poland",7  ],
                ["Nepal","Sweden",9  ],
                ["Nepal","Switzerland",18  ],
                ["New Zealand","Germany",7  ],
                ["Pakistan","Austria",375  ],
                ["Pakistan","Azerbaijan",45  ],
                ["Pakistan","Belgium",345  ],
                ["Pakistan","Bosnia and Herzegovina",5  ],
                ["Pakistan","Bulgaria",30  ],
                ["Pakistan","Cyprus",21  ],
                ["Pakistan","Czechia",8  ],
                ["Pakistan","Denmark",66  ],
                ["Pakistan","Finland",75  ],
                ["Pakistan","France",2742  ],
                ["Pakistan","United Kingdom of Great Britain and Northern Ireland",8245  ],
                ["Pakistan","Georgia",11  ],
                ["Pakistan","Germany",8788  ],
                ["Pakistan","Greece",1279  ],
                ["Pakistan","Croatia",10  ],
                ["Pakistan","Hungary",92  ],
                ["Pakistan","Iceland",22  ],
                ["Pakistan","Ireland",391  ],
                ["Pakistan","Italy",16570  ],
                ["Pakistan","Lithuania",5  ],
                ["Pakistan","North Macedonia",5  ],
                ["Pakistan","Malta",59  ],
                ["Pakistan","Netherlands",768  ],
                ["Pakistan","Norway",77  ],
                ["Pakistan","Poland",29  ],
                ["Pakistan","Portugal",80  ],
                ["Pakistan","Romania",28  ],
                ["Pakistan","Russian Federation",6  ],
                ["Pakistan","Spain",458  ],
                ["Pakistan","Serbia and Kosovo: S/RES/1244 (1999)",5  ],
                ["Pakistan","Slovakia",8  ],
                ["Pakistan","Slovenia",5  ],
                ["Pakistan","Sweden",609  ],
                ["Pakistan","Switzerland",296  ],
                ["Pakistan","Ukraine",10  ],
                ["Philippines","Austria",19  ],
                ["Philippines","Cyprus",12  ],
                ["Philippines","France",7  ],
                ["Philippines","United Kingdom of Great Britain and Northern Ireland",61  ],
                ["Philippines","Germany",37  ],
                ["Philippines","Greece",7  ],
                ["Philippines","Italy",17  ],
                ["Philippines","Netherlands",6  ],
                ["Philippines","Russian Federation",5  ],
                ["Philippines","Sweden",6  ],
                ["Philippines","Switzerland",12  ],
                ["Singapore","United Kingdom of Great Britain and Northern Ireland",5  ],
                ["Singapore","Germany",7  ],
                ["Solomon Islands","Germany",6  ],
                ["Viet Nam","Austria",5  ],
                ["Viet Nam","Belgium",23  ],
                ["Viet Nam","Cyprus",5  ],
                ["Viet Nam","Czechia",14  ],
                ["Viet Nam","Finland",8  ],
                ["Viet Nam","France",8018  ],
                ["Viet Nam","United Kingdom of Great Britain and Northern Ireland",2772  ],
                ["Viet Nam","Germany",1096  ],
                ["Viet Nam","Greece",5  ],
                ["Viet Nam","Ireland",10  ],
                ["Viet Nam","Monaco",7  ],
                ["Viet Nam","Netherlands",11  ],
                ["Viet Nam","Norway",38  ],
                ["Viet Nam","Poland",5  ],
                ["Viet Nam","Spain",7  ],
                ["Viet Nam","Slovakia",16  ],
                ["Viet Nam","Sweden",19  ],
                ["Viet Nam","Switzerland",760  ],
                ["Thailand","Denmark",5  ],
                ["Thailand","France",15  ],
                ["Thailand","United Kingdom of Great Britain and Northern Ireland",36  ],
                ["Thailand","Germany",27  ],
                ["Tajikistan","Austria",260  ],
                ["Tajikistan","Belgium",11  ],
                ["Tajikistan","Belarus",10  ],
                ["Tajikistan","Czechia",5  ],
                ["Tajikistan","Denmark",6  ],
                ["Tajikistan","Finland",9  ],
                ["Tajikistan","France",121  ],
                ["Tajikistan","United Kingdom of Great Britain and Northern Ireland",14  ],
                ["Tajikistan","Georgia",5  ],
                ["Tajikistan","Germany",1178  ],
                ["Tajikistan","Greece",5  ],
                ["Tajikistan","Iceland",5  ],
                ["Tajikistan","Lithuania",85  ],
                ["Tajikistan","Latvia",5  ],
                ["Tajikistan","Rep. of Moldova",6  ],
                ["Tajikistan","Netherlands",28  ],
                ["Tajikistan","Norway",5  ],
                ["Tajikistan","Poland",148  ],
                ["Tajikistan","Russian Federation",31  ],
                ["Tajikistan","Spain",5  ],
                ["Tajikistan","Sweden",62  ],
                ["Tajikistan","Switzerland",26  ],
                ["Tajikistan","Ukraine",23  ],
                ["Turkmenistan","Austria",8  ],
                ["Turkmenistan","Czechia",7  ],
                ["Turkmenistan","France",41  ],
                ["Turkmenistan","United Kingdom of Great Britain and Northern Ireland",21  ],
                ["Turkmenistan","Germany",90  ],
                ["Turkmenistan","Greece",7  ],
                ["Turkmenistan","Luxembourg",5  ],
                ["Turkmenistan","Rep. of Moldova",5  ],
                ["Turkmenistan","Netherlands",18  ],
                ["Turkmenistan","Norway",5  ],
                ["Turkmenistan","Poland",34  ],
                ["Turkmenistan","Russian Federation",51  ],
                ["Turkmenistan","Sweden",16  ],
                ["Turkmenistan","Switzerland",5  ],
                ["Turkmenistan","Ukraine",7  ],
                ["Uzbekistan","Albania",5  ],
                ["Uzbekistan","Austria",44  ],
                ["Uzbekistan","Azerbaijan",5  ],
                ["Uzbekistan","Belgium",37  ],
                ["Uzbekistan","Cyprus",5  ],
                ["Uzbekistan","Czechia",35  ],
                ["Uzbekistan","Denmark",9  ],
                ["Uzbekistan","Finland",10  ],
                ["Uzbekistan","France",300  ],
                ["Uzbekistan","United Kingdom of Great Britain and Northern Ireland",70  ],
                ["Uzbekistan","Germany",154  ],
                ["Uzbekistan","Greece",12  ],
                ["Uzbekistan","Croatia",5  ],
                ["Uzbekistan","Hungary",6  ],
                ["Uzbekistan","Ireland",17  ],
                ["Uzbekistan","Lithuania",17  ],
                ["Uzbekistan","Latvia",11  ],
                ["Uzbekistan","Rep. of Moldova",8  ],
                ["Uzbekistan","Netherlands",9  ],
                ["Uzbekistan","Norway",155  ],
                ["Uzbekistan","Poland",16  ],
                ["Uzbekistan","Russian Federation",80  ],
                ["Uzbekistan","Spain",13  ],
                ["Uzbekistan","Slovakia",5  ],
                ["Uzbekistan","Sweden",495  ],
                ["Uzbekistan","Switzerland",57  ],
                ["Uzbekistan","Ukraine",40  ]
              ],
            name: "Asia Pacific to Europe"
          }
    ]
  };

  //what will actually be displayed
  return (
    <div>
      <button onClick={() => handleTypeChange(type)}>
        Change Type To {type === "sankey" ? "dependencywheel" : "sankey"}
      </button>
      <HighchartsReact highcharts={Highcharts} options={options} />
    </div>
  );
};


export default App;
